apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-microservice
  template:
    metadata:
      labels:
        app: authorization-microservice
    spec:
      containers:
        - name: authorization-microservice
          image: 2741/authorization-microservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY